Vcb 6 leds on ct board
ZHAW-FS22-PM4/Virtual-CT-Board pull request #18
Opened 2022-04-09 10:39 UTC by akrosis

2022-04-11 18:45 UTC, stefenz requested changes
Looks good to me, just the labelling in the UI is not correct yet

2022-04-11 18:45 UTC, stefenz commented on src/components/board/led/index.tsx
> +              <div className="label">{'S' + key}</div>
The LEDs should not be labeled with S*. Please label it like on the real board.

2022-04-11 18:46 UTC, stefenz commented on src/components/board/led/index.tsx
> +              <div className="label">{'S' + key}</div>
And please merge in the actual master so this pr is ready to merge

2022-04-14 05:31 UTC, stefenz commented on src/components/board/led/index.tsx
> +              <div className="label">{'S' + key}</div>
And add some tests ;)

2022-04-19 17:31 UTC, stefenz commented on src/components/board/led/index.tsx
> +              <div className="label">{'S' + key}</div>
Sorry about the tests - my fault.

Unfortunately the labels are now very tiny and not readable. Wouldn't you label them like on the physical board, where just the leds at the edges of each four are  labeled with numbers and between with dots (...)?

2022-04-19 21:56 UTC, m-dot-wigger requested changes
install npm package to get imports in alphabetical order and format files

as mentioned of Stefan only label highest and lowest so that labels can be bigger.

2022-04-20 20:14 UTC, clooudch commented on src/board/devices/output/leds.ts
>    public isVolatile = false
Should probably be `true`. I think LED's lose their state when the board is reset.

2022-04-20 20:37 UTC, akrosis commented on src/components/board/led/index.tsx
> +export class Led extends React.Component<LedProps, LedState> {
Sounds good to me, should we do this in a seperate branch, after everything is merged from this sprint?
Or should I do the changes in this branch?

2022-04-20 20:42 UTC, akrosis commented on src/components/board/index.tsx
>  export class Board extends React.Component {
Same question as with te suffixes, should I do this here or do we make a seperate branch after everything from the other stories is merged?

2022-04-20 20:44 UTC, akrosis commented on src/components/board/index.tsx
> +import { Led } from './led'
Im not sure I understand what you mean here, the order of the imports is alphabetical right?

2022-04-20 21:02 UTC, clooudch commented on src/components/board/index.tsx
> +import { Led } from './led'
I am sorry. I have created this comment some time ago before we had this new import sort plugin for prettier.

2022-04-20 21:03 UTC, clooudch commented on src/components/board/led/index.tsx
> +  private update() {
Yes. Perfect. Thank you 😄 .

2022-04-20 21:04 UTC, clooudch commented on src/components/board/led/index.tsx
> +export class Led extends React.Component<LedProps, LedState> {
For the files which are affected by you PR you can change it here and for the other files we change it along the way. I don't think that we need a dedicated User Story or Bug for this. It's actually only a very small change.

2022-04-20 21:05 UTC, clooudch commented on src/components/board/index.tsx
>  export class Board extends React.Component {
I close this comment here. As it's covered in another conversation.

2022-04-20 21:16 UTC, akrosis commented on src/components/board/led/index.tsx
> +export class Led extends React.Component<LedProps, LedState> {
done

2022-04-20 21:29 UTC, clooudch approved these changes

2022-04-20 21:34 UTC, merged

2022-04-20 21:35 UTC, m-dot-wigger approved these changes