Assembler
ZHAW-FS22-PM4/Virtual-CT-Board pull request #24
Opened 2022-04-27 03:44 UTC by clooudch

2022-04-27 14:01 UTC, clooudch commented on src/board/index.ts
> +   * @returns
Missing documentation

2022-04-27 16:08 UTC, ni507 commented
@clooudch I fixed the known issue (B instruction is currently unable to handle negative pc increments) in the branch https://github.com/ZHAW-FS22-PM4/Virtual-CT-Board/tree/vcb-13-unconditional-jump

2022-04-27 19:54 UTC, clooudch commented
Maybe it would be better if we could avoid creating a dedicated type just for this one scenario with 11 bits. Can't we make the binary base type non-abstract and just instantiate it using the correct settings.

Imagine having:
```typescript
export class BinaryValue {
  public readonly value: number
  public readonly length: number
  public readonly maxValue: number
  constructor(value: number, length: number) {
    this.value = value
    this.length= length
    this.maxValue = Math.pow(2, length)
  }
}

export class Word extends BinaryValue {
  constructor(value: number) {
    super(value, 32)
  }
}

function demo() {
  const imm11 = new BinaryValue(-20, 11)
}
```

2022-04-28 07:34 UTC, ni507 submitted a review, later dismissed
In general, things are looking good. However, with such big changes it is difficult to look at everything in detail, so I rather just looked at it a bit roughly.

2022-04-28 07:34 UTC, ni507 commented on src/assembler/elf/utils.ts
> + * @param file the filearam type the type of symbol
typo 'filearam' and wrong param name

2022-04-28 07:34 UTC, ni507 commented on src/instruction/interfaces.ts
>     * @param opcode the opcode of the instruction to be executed
Missing param docs for `registers` and `memory`

2022-04-28 07:34 UTC, ni507 commented on src/instruction/interfaces.ts
> +  [name: string]: Word
The label offsets for the jump instructions are never greater than a halfword. Is this change to the type `Word`required for pseudo instructions?

2022-04-28 15:31 UTC, ni507 commented on src/instruction/interfaces.ts
> +  [name: string]: Word
Nevermind. The offset for the "BL" instruction is larger than a halfword.

2022-04-28 21:13 UTC, ni507 commented on src/board/processor.ts
> +      opcode.push(this.memory.readHalfword(pc.add(i)))
Little bug. PC register should be incremented by `i * 2` to read the correct halfword from the memory.
Fixed this in the branch vcb-13-unconditional-jump.

2022-04-29 07:21 UTC, m-dot-wigger requested changes
as far as I can see LDR R3, label is only possible for LDR and not for LDRB or LDRH 
![grafik](https://user-images.githubusercontent.com/56474048/165895962-c8722395-187e-4b1f-bc64-dcc7a2072046.png)


 codecoverage is not best, but will increase with branches depending on this:
![grafik](https://user-images.githubusercontent.com/56474048/165896056-9b871ec0-edc9-405a-8203-c27e3fb15845.png)


I don't know if it helps readability if on 16 bit instruction opcode array is set to `opcode = opcode[0]` in the onExecuteInstruction

2022-04-29 07:21 UTC, m-dot-wigger commented on src/assembler/encoder.ts
> +function writeDataInsruction(
typo Instruction

2022-04-29 07:23 UTC, m-dot-wigger commented
This PR will be merged into master for VCB-93 Data sections, right?
So I can merge this into my bug branch to resolve merge conflicts

2022-05-01 21:25 UTC, deflox commented
Regarding "parser now enforces upper case for the instruction name.". Just as a sidenote: The real CT board allows lowercase instruction names.

2022-05-03 05:46 UTC, clooudch commented
> Regarding "parser now enforces upper case for the instruction name.". Just as a sidenote: The real CT board allows lowercase instruction names.

It does still support lowercase instructions but they are now converted to upper case during parsing. So, that the 'canEncodeInstruction' always receives upper case.

2022-05-03 20:03 UTC, m-dot-wigger approved these changes
All looks good now can be merged.

Also as deputy for Silvan

2022-05-04 11:47 UTC, clooudch commented
> as far as I can see LDR R3, label is only possible for LDR and not for LDRB or LDRH ![grafik](https://user-images.githubusercontent.com/56474048/165895962-c8722395-187e-4b1f-bc64-dcc7a2072046.png)
> 
> codecoverage is not best, but will increase with branches depending on this: ![grafik](https://user-images.githubusercontent.com/56474048/165896056-9b871ec0-edc9-405a-8203-c27e3fb15845.png)
> 
> I don't know if it helps readability if on 16 bit instruction opcode array is set to `opcode = opcode[0]` in the onExecuteInstruction

Test will be added in the pull requests were the features are supposed to be added. So, this PR will only contain tests for data sections but not for pseudo instructions.

2022-05-04 12:53 UTC, closed without merging

2022-05-04 12:55 UTC, clooudch commented
This PR has been closed in favor of #30.